### ISSUE TITLE
Plans for Postgres support?

### ISSUE THREAD

**Issue by trbouma** [cashubtc/cashu#104]
Just wondering if there are plans to enable postgres backend support? I am starting to look at the code that is commented out to see if it is easy to do or not. Before I start, just wondering if you have started anything yet^

**Comment by callebtc** [comment]
I haven't tested it myself but it might be it works out of the box since I have reused the db logic from lnbits. Please report back if you try it out!

**Comment by trbouma** [comment]
Ok, I will see if I can get it to work and report back!

**Comment by callebtc** [comment]
It worked!
