### ISSUE TITLE
[Mint] Update to latest `fastapi`

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu#178]
The Cashu mint sometimes (very rarely) stops for no apparent reason. It would be worth trying to update fastapi to the latest version to see if it fixes the issue.

**Comment by callebtc** [comment]
I think this is something that @dni may be particularly good at :)

**Comment by dni** [comment]
hehe :) i can do it :P

**Comment by dni** [comment]
there you go https://github.com/cashubtc/cashu/pull/302
