### ISSUE TITLE
[Mint] Mint gets stuck sometimes

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu#195]
I don't know what the reason is but when it happens, the mint stops responding to any further API calls and needs to be killed with `kill -9`.

Happens rarely but often enough to be an annoyance. Maybe something to do with Fastapi.

**Comment by callebtc** [comment]
I thought the transaction-lock on the db might solve the issue in #217 but it didn't.

**Comment by callebtc** [comment]
Caught the mint at getting stuck with excessive logging

```
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.78 | TRACE | melt called
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.78 | TRACE | attempting lock table proofs_pending
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.78 | TRACE | locked table proofs_pending
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.78 | TRACE | setting proofs pending
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.78 | TRACE | crud: _validate_proofs_pending validating proofs
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.78 | TRACE | crud: _validate_proofs_pending got proofs pending
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.78 | TRACE | crud: _set_proofs_pending setting proof ............... as pending
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | set proofs as pending
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | Validating proof with keyset I2yN+iRYfkzT.
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.79 | TRACE | verified proofs
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.85 | TRACE | check_fees: checking lightning invoice: <payment_hash>
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.94 | TRACE | check_fees: paid: still pending
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.94 | TRACE | paying lightning invoice
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.94 | TRACE | _pay_lightning_invoice: paying Lightning invoice lnbc100u1.................
May 16 13:13:02 caph poetry[2362686]: 2023-05-16 13:13:02.99 | TRACE | _pay_lightning_invoice: Lightning wallet balance: ...........
```


Looking at the LNbits logs for this payment, it seems the invoice took 10 minutes to fail (13:23 ish) but it failed. The mint never got notice of this but got stuck in this step. All other routes are stuck as well.

**Comment by AngusP** [comment]
Also noticed the `timeout=None` on the pay lighting invoice request -- pre #230 that for sure would cause these long lockups.

No-timeout on the request isn't great, but seems to work for now -- ideal solution may be to try pay it quickly once, if that fails then retry using a [background task](https://fastapi.tiangolo.com/tutorial/background-tasks/) (maybe into the DB too as an 'obligation' of the mint) so the user gets a response fairly promptly (HTTP 202) and then some way to check back in on whether the payment has completed or not. But that's a fair bit more complicated

**Comment by callebtc** [comment]
Yeah that's a problem but I think we can't avoid having a background check / startup task at some point, especially because the wallet backend or Cashu might restart during a payment.

We'd have to give the invoices in the invoice table a payment state and have Cashu loop through all pending invoices and check with the backend for the payment state (at startup).

We'd also have to remember the tokens associated with each invoice in the db and burn or unlock them according to the payment state.

**Comment by callebtc** [comment]
If we return the "pending payment" response of /melt immediately to the user wallet, we'd have to add that to the NUT as well!
