### ISSUE TITLE
[BUG] /pay not loading proofs results in zero balance assumption

### ISSUE THREAD

**Issue by dyKiU** [cashubtc/cashu#309]
During work on tests with lighting enabled the bug became apparent. The invoice cannot be paid because mint wallet always has a zero balance. The fix is simple and involves calling load_proofs after this [line](https://github.com/cashubtc/cashu/blob/87c0adc60d66357d324b257bc2f7a336e8a102c3/cashu/wallet/api/router.py#L90)

**Comment by callebtc** [comment]
Closed in https://github.com/cashubtc/cashu/pull/310
