### ISSUE TITLE
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://8333.space:3338/melt

### ISSUE THREAD

**Issue by RyanSinger** [cashubtc/cashu#49]
Can easily receive lightning payments, but when I try to send I get an error. Blackholes for money are bad.

```
➜  ~ cashu pay lnbc49500n1p34lahtpp5k8dtlv5ylf3470sknmypw5pkcpcdm8gyu3kqptdnvkhtpm7yrg3qdqqcqzzgxqyz5vqrzjqwnvuc0u4txn35cafc7w94gxvq5p3cu9dd95f7hlrh0fvs46wpvhd9gcnskmvfa4r5qqqqryqqqqthqqpyrzjqw8c7yfutqqy3kz8662fxutjvef7q2ujsxtt45csu0k688lkzu3ld9gcnskmvfa4r5qqqqryqqqqthqqpysp5s6e278284n2vpcz8zsk7225zuur52yygv9xp9tckcrugjmn7afnq9qypqsq6lk32le7xefrlnatnhrs2h9fzl4zlu454pxh9h4f3ljjva54tjfzxu0t3qngtdhtkqvlwrxje8djzrgzu4992x02aawpjppzdh0cgzspgnr78t
Balance: 5000 sat (available: 5000 sat in 8 tokens)
Pay 4950 sat (4999 sat incl. fees)? [Y/n]: Y
Paying Lightning invoice ...
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://8333.space:3338/melt
```

**Comment by callebtc** [comment]
Hi, thanks for the issue. First of all, this is a demo instance so don't expect it to be perfect all the time. Second, this is most certainly an error from the Lightning node backend (I just tried to pay and it worked with another destination). Where does this invoice go to Muun? Maybe the fees are not enough. Please try another destination to confirm that it works.

**Comment by RyanSinger** [comment]
Ok. Just tried to pay a 4000 sat invoice and it went through. Feel free to close this issue.
