### ISSUE TITLE
Pyconfig.h File not found

### ISSUE THREAD

**Issue by LightRider5** [cashubtc/cashu#50]
On MacOS I got this error after `pip install cashu`:

`Pyconfig.h File not found` during spec256 installation. 

Fixed it with: 

`CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/Users/your/path/python3.7m
`

**Comment by callebtc** [comment]
Thank you!

According to [this stackexchange post](https://github.com/nanocurrency/nano-node/issues/1505#issuecomment-450720028), you can find the correct include path (to be put into `CPLUS_INCLUDE_PATH`) using the command: `python3.7-config --includes --libs`
