### ISSUE TITLE
Need way to pass in metadata into invoice

### ISSUE THREAD

**Issue by trbouma** [cashubtc/cashu#59]
I have been integrating Lightning Addresses. I have everything working but I have hit a snag where the invoice fails verification on the LN WALLET side.

This is step 7 of the protocol here https://github.com/lnurl/luds/blob/luds/06.md

7. LN WALLET Verifies that h tag in provided invoice is a hash of metadata string converted to byte array in UTF-8 encoding.

Everything works, it is just an issue of dealing with the LN WALLET protocol, where the LN WALLET needs to additionally verify the invoice using the h tag before proceeding. Otherwise the invoice is fine

Currently there is no way to pass in the hash of metadata during invoice generation. 

My code snippet is below for my managed wallet instance below:

```
wallet =  Wallet(mint_url, os.path.join(".","wallets", wallet_uuid))
asyncio.run(init_wallet(wallet))
asyncio.run(wallet.load_mint())

invoice = asyncio.run(wallet.request_mint(amount))

return  {   "pr": invoice.pr,
                "routes": []
            } 
```

The invoice.pr is fine. I have tested the return result and the invoice is valid. What is missing in the h tag with the necessary hashed metadata and the LN WALLET fails on step 7 above.

Appreciate any approaches to solving this protocol snag.

**Comment by trbouma** [comment]
Upon further investigation the necessary components are there and accessible via cashu.core.bolt11, but it looks like the invoice is signed by the funding source, so it can't be modified after the fact. So there needs to be a way to pass the description_hash down through the request_mint method. I am sure this can be generalized to any option.

**Comment by trbouma** [comment]
I created a pull request so you can see the files I changed

**Comment by callebtc** [comment]
This is an LNURL function that should not be part of Cashu itself.
