### ISSUE TITLE
split of promises is not as expected.

### ISSUE THREAD

**Issue by lackrobin** [cashubtc/cashu#84]
`split of promises is not as expected.`

When calling the the /split endpoint on LNBits. Does the mint dictate what the split looks like? If yes, what is the reason behind this? And what algorithm is used to make the splits? 
I was just wondering about this, since I'm trying to implement my own client.

**Comment by callebtc** [comment]
Hey there, I'm so sorry that this post slipped under my radar. Are you still having issues with this? Please join our Telegram channel if you developed something! :)

**Comment by callebtc** [comment]
Closing until more comes up!
