### ISSUE TITLE
when melting tokens, preimage in Response is null (LNBits) 

### ISSUE THREAD

**Issue by lackrobin** [cashubtc/cashu#85]
Melting tokens & everything seems to work fine, but the preimage is not returned (see screenshot)

![image](https://user-images.githubusercontent.com/7565918/210738534-cdfc7224-00da-448e-ab87-e76defcc8a9b.png)

**Comment by callebtc** [comment]
This is most probably because LNbits uses a funding source that didn't provide the preimage. It should be in there if you use an lnbits with a funding source like LND or CLN. 


Thank you for the Issue and please feel free to join our Telegram channel: https://t.me/CashuBTC
